### ISSUE TITLE
My Drives> Cannot Horizontal scroll past current week

### ISSUE THREAD

**Issue by Katieesq** [clinicaccess/casn-app#34]
Not sure what about this current build implementation caused this (perhaps a ripple effect of issue #15 ) but we cannot scroll past the current week on the My Drives screen. Looks like the rides are not loading, per the console.

![image](https://user-images.githubusercontent.com/24197365/76691781-9f8a9b80-661c-11ea-91f4-024e29bef9f5.png)

**Comment by ahollyer** [comment]
Just noting that this issue was caused by the code duplication between the "View Schedule" and "My Drives" component. I resolved it by copying the bug fix from "View Schedule" to "My Drives", but am now working on extracting the duplicated code into a shared service to prevent these types of bugs in the future.
